import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:yellowshifts/core/permissions/station_access_context.dart';
import 'package:yellowshifts/features/employees/data/employee_repository.dart';
import 'package:yellowshifts/features/employees/domain/employee_details.dart';
import 'package:yellowshifts/features/employees/presentation/widgets/reset_password_dialog.dart';
import 'package:yellowshifts/features/stations/domain/station_membership.dart';
import 'package:yellowshifts/features/stations/presentation/active_station_provider.dart';
import 'package:yellowshifts/l10n/app_localizations.dart';

class MockEmployeeRepo implements EmployeeRepository {
  String? lastResetPassword;
  String? lastResetUserId;

  @override
  Future<List<EmployeeDetails>> getStationEmployees({
    required String stationId,
    String? search,
    StationRole? role,
    MembershipStatus? status,
  }) async =>
      [];

  @override
  Future<Map<String, dynamic>> createEmployee({
    required String stationId,
    required String firstName,
    required String lastName,
    String? email,
    String? phone,
    required StationRole role,
    String? employeeCode,
  }) async =>
      {};

  @override
  Future<Map<String, dynamic>> updateEmployeeProfile({
    required String stationId,
    required String userId,
    required String membershipId,
    required String firstName,
    required String lastName,
    String? email,
    String? phone,
    String? preferredLocale,
    required StationRole role,
    required MembershipStatus status,
    String? employeeCode,
  }) async =>
      {};

  @override
  Future<void> updateMembership({
    required String stationId,
    required String membershipId,
    required StationRole role,
    required MembershipStatus status,
    String? employeeCode,
  }) async {}

  @override
  Future<String> resetEmployeePassword({
    required String stationId,
    required String userId,
    String? newPassword,
  }) async {
    lastResetUserId = userId;
    lastResetPassword = newPassword;
    return newPassword ?? 'Ys#AutoGeneratedPass123';
  }

  @override
  Future<void> revokeEmployeeSessions({
    required String stationId,
    required String userId,
  }) async {}
}

void main() {
  final testEmployee = EmployeeDetails(
    membershipId: 'mem-101',
    stationId: 'st-202',
    userId: 'usr-303',
    role: StationRole.employee,
    status: MembershipStatus.active,
    employeeCode: 'EMP-303',
    joinedAt: DateTime(2026, 1, 1),
    firstName: 'Sarah',
    lastName: 'Connor',
    email: 'sarah@station.com',
  );

  final adminMembership = StationMembership(
    id: 'mem-admin',
    stationId: 'st-202',
    userId: 'usr-admin',
    role: StationRole.admin,
    status: MembershipStatus.active,
    joinedAt: DateTime(2026, 1, 1),
    createdAt: DateTime(2026, 1, 1),
    updatedAt: DateTime(2026, 1, 1),
  );

  late MockEmployeeRepo mockRepo;

  setUp(() {
    mockRepo = MockEmployeeRepo();
  });

  Widget createTestWidget() {
    return ProviderScope(
      overrides: [
        employeeRepositoryProvider.overrideWithValue(mockRepo),
        activeStationIdProvider
            .overrideWith((ref) => ActiveStationIdNotifier(null, 'st-202')),
        stationAccessContextProvider.overrideWithValue(
          StationAccessContext(
            isAuthenticated: true,
            hasActiveStation: true,
            activeStationId: 'st-202',
            activeMembership: adminMembership,
          ),
        ),
      ],
      child: MaterialApp(
        localizationsDelegates: AppLocalizations.localizationsDelegates,
        supportedLocales: AppLocalizations.supportedLocales,
        locale: const Locale('en'),
        home: Scaffold(
          body: ResetEmployeePasswordDialog(employee: testEmployee),
        ),
      ),
    );
  }

  group('ResetEmployeePasswordDialog UI & Flow Tests', () {
    testWidgets('Renders initial password reset dialog properly',
        (tester) async {
      await tester.pumpWidget(createTestWidget());
      await tester.pumpAndSettle();

      expect(find.text('Reset Employee Password'), findsOneWidget);
      expect(find.text('Set Password'), findsOneWidget);
      expect(find.text('Generate Random'), findsOneWidget);
      expect(find.text('Cancel'), findsOneWidget);
    });

    testWidgets('Submitting with custom password updates user password',
        (tester) async {
      await tester.pumpWidget(createTestWidget());
      await tester.pumpAndSettle();

      // Enter a custom password
      await tester.enterText(find.byType(TextFormField), 'MyCustomSecret123');
      await tester.pumpAndSettle();

      // Click Set Password
      await tester.tap(find.text('Set Password'));
      await tester.pumpAndSettle();

      expect(mockRepo.lastResetUserId, 'usr-303');
      expect(mockRepo.lastResetPassword, 'MyCustomSecret123');

      // Success screen should show
      expect(find.text('Password Set Successfully'), findsOneWidget);
      expect(find.text('MyCustomSecret123'), findsOneWidget);
      expect(find.text('Copy Password'), findsOneWidget);
      expect(find.text('Close'), findsOneWidget);
    });

    testWidgets(
        'Clicking Generate Random populates field and generates valid password',
        (tester) async {
      await tester.pumpWidget(createTestWidget());
      await tester.pumpAndSettle();

      // Click Generate Random
      await tester.tap(find.text('Generate Random'));
      await tester.pumpAndSettle();

      // Click Set Password
      await tester.tap(find.text('Set Password'));
      await tester.pumpAndSettle();

      expect(mockRepo.lastResetUserId, 'usr-303');
      expect(mockRepo.lastResetPassword, isNotNull);
      expect(mockRepo.lastResetPassword!.length, greaterThanOrEqualTo(6));
      expect(find.text('Password Set Successfully'), findsOneWidget);
    });

    testWidgets(
        'Submitting empty password generates default temporary password',
        (tester) async {
      await tester.pumpWidget(createTestWidget());
      await tester.pumpAndSettle();

      // Click Set Password directly without entering anything
      await tester.tap(find.text('Set Password'));
      await tester.pumpAndSettle();

      expect(mockRepo.lastResetUserId, 'usr-303');
      expect(mockRepo.lastResetPassword, isNull);
      expect(find.text('Password Set Successfully'), findsOneWidget);
      expect(find.text('Ys#AutoGeneratedPass123'), findsOneWidget);
    });

    testWidgets('Validates minimum length if text entered is less than 6 chars',
        (tester) async {
      await tester.pumpWidget(createTestWidget());
      await tester.pumpAndSettle();

      // Enter short password
      await tester.enterText(find.byType(TextFormField), '123');
      await tester.pumpAndSettle();

      // Click Set Password
      await tester.tap(find.text('Set Password'));
      await tester.pumpAndSettle();

      expect(
          find.text('Password must be at least 6 characters'), findsOneWidget);
      expect(mockRepo.lastResetUserId, isNull);
    });
  });
}
